--
-- PostgreSQL database dump
--

\restrict oBfVbCJTXPZXNTgFrJJaTHByDJQmeqnjLjNvQl9i2V2fswDRq1XGUrHbpyXLgsg

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: scoremaster; Type: SCHEMA; Schema: -; Owner: tiago
--

CREATE SCHEMA scoremaster;


ALTER SCHEMA scoremaster OWNER TO tiago;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: card; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.card (
    id bigint NOT NULL,
    home_card boolean NOT NULL,
    minute character varying(255),
    yellow_card boolean NOT NULL,
    id_player bigint,
    id_card bigint
);


ALTER TABLE scoremaster.card OWNER TO tiago;

--
-- Name: card_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: club; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.club (
    id bigint NOT NULL,
    city character varying(255),
    country character varying(255),
    name character varying(255),
    foundation timestamp(6) without time zone
);


ALTER TABLE scoremaster.club OWNER TO tiago;

--
-- Name: club_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.club ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.club_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.game (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    date timestamp(6) without time zone,
    id_away_club bigint,
    id_home_club bigint,
    id_stadium bigint
);


ALTER TABLE scoremaster.game OWNER TO tiago;

--
-- Name: game_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goal; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.goal (
    id bigint NOT NULL,
    home_goal boolean NOT NULL,
    minute character varying(255),
    own_goal boolean NOT NULL,
    penalty_goal boolean NOT NULL,
    id_player bigint,
    id_game bigint
);


ALTER TABLE scoremaster.goal OWNER TO tiago;

--
-- Name: goal_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.goal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.goal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.player (
    id bigint NOT NULL,
    birthday timestamp(6) without time zone,
    country character varying(255),
    height double precision NOT NULL,
    name character varying(255),
    right_handed boolean NOT NULL,
    weight double precision NOT NULL
);


ALTER TABLE scoremaster.player OWNER TO tiago;

--
-- Name: player_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stadium; Type: TABLE; Schema: scoremaster; Owner: tiago
--

CREATE TABLE scoremaster.stadium (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    city character varying(255),
    country character varying(255),
    name character varying(255),
    foundation date
);


ALTER TABLE scoremaster.stadium OWNER TO tiago;

--
-- Name: stadium_id_seq; Type: SEQUENCE; Schema: scoremaster; Owner: tiago
--

ALTER TABLE scoremaster.stadium ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME scoremaster.stadium_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: card; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.card (id, home_card, minute, yellow_card, id_player, id_card) FROM stdin;
\.


--
-- Data for Name: club; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.club (id, city, country, name, foundation) FROM stdin;
5	Brasilia	Brasil	Brasil	1913-12-31 00:00:00
6	Tóquio	Japão	Japão	1920-12-31 00:00:00
7	Cidade do México	México	México	1926-12-31 00:00:00
8	Roma	Itália	Itália	1898-03-14 00:00:00
9	Madri	Espanha	Espanha	1913-09-28 00:00:00
10	Montevídeo	Uruguai	Uruguai	1900-03-29 00:00:00
11	Papeete	Taiti	Taiti	1988-12-31 00:00:00
12	Abuja	Nigéria	Nigéria	1944-12-31 00:00:00
\.


--
-- Data for Name: game; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.game (id, capacity, date, id_away_club, id_home_club, id_stadium) FROM stdin;
\.


--
-- Data for Name: goal; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.goal (id, home_goal, minute, own_goal, penalty_goal, id_player, id_game) FROM stdin;
\.


--
-- Data for Name: player; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.player (id, birthday, country, height, name, right_handed, weight) FROM stdin;
1	1998-12-31 22:00:00	Brasil	1	Teste	t	85.9
\.


--
-- Data for Name: stadium; Type: TABLE DATA; Schema: scoremaster; Owner: tiago
--

COPY scoremaster.stadium (id, capacity, city, country, name, foundation) FROM stdin;
1	72788	Brasilia	Brasil	Estádio Nacional Mané Garrincha	1974-01-01
2	78838	Rio de Janeiro	Brasil	Estádio Jornalista Mário Filho (Maracanã)	1950-01-01
4	46154	São Lourenço da Mata (PE)	Brasil	Arena Pernambuco	2013-01-01
5	61846	Belo Horizonte	Brasil	Estádio Gov. Magalhães Pinto (Mineirão)	1965-01-01
3	63903	Fortaleza	Brasil	Governador Plácido Aderaldo Castelo (Castelão)	1973-01-01
6	50000	Salvador	Brasil	Arena Fonte Nova	2013-01-01
\.


--
-- Name: card_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.card_id_seq', 1, false);


--
-- Name: club_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.club_id_seq', 12, true);


--
-- Name: game_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.game_id_seq', 1, false);


--
-- Name: goal_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.goal_id_seq', 1, false);


--
-- Name: player_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.player_id_seq', 1, true);


--
-- Name: stadium_id_seq; Type: SEQUENCE SET; Schema: scoremaster; Owner: tiago
--

SELECT pg_catalog.setval('scoremaster.stadium_id_seq', 6, true);


--
-- Name: card card_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.card
    ADD CONSTRAINT card_pkey PRIMARY KEY (id);


--
-- Name: club club_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.club
    ADD CONSTRAINT club_pkey PRIMARY KEY (id);


--
-- Name: game game_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (id);


--
-- Name: goal goal_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.goal
    ADD CONSTRAINT goal_pkey PRIMARY KEY (id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: stadium stadium_pkey; Type: CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.stadium
    ADD CONSTRAINT stadium_pkey PRIMARY KEY (id);


--
-- Name: card fk14nh8vjd1k3jb4m1cks3l75hm; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.card
    ADD CONSTRAINT fk14nh8vjd1k3jb4m1cks3l75hm FOREIGN KEY (id_card) REFERENCES scoremaster.game(id);


--
-- Name: game fk1y2lr2qfq1e1pbc4qeb3epubl; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.game
    ADD CONSTRAINT fk1y2lr2qfq1e1pbc4qeb3epubl FOREIGN KEY (id_home_club) REFERENCES scoremaster.club(id);


--
-- Name: game fkc1jx206vdx41893i4jhbqwo72; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.game
    ADD CONSTRAINT fkc1jx206vdx41893i4jhbqwo72 FOREIGN KEY (id_away_club) REFERENCES scoremaster.club(id);


--
-- Name: goal fkdh684aa7tlql9b6rqigtyha6y; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.goal
    ADD CONSTRAINT fkdh684aa7tlql9b6rqigtyha6y FOREIGN KEY (id_game) REFERENCES scoremaster.game(id);


--
-- Name: goal fknw0lrv1du2yrvgsu6sjp8oc02; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.goal
    ADD CONSTRAINT fknw0lrv1du2yrvgsu6sjp8oc02 FOREIGN KEY (id_player) REFERENCES scoremaster.player(id);


--
-- Name: game fkq4v9ccmbfmugp3e7300lkuprq; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.game
    ADD CONSTRAINT fkq4v9ccmbfmugp3e7300lkuprq FOREIGN KEY (id_stadium) REFERENCES scoremaster.stadium(id);


--
-- Name: card fkrjuhhst8mclavtfueejmpr6br; Type: FK CONSTRAINT; Schema: scoremaster; Owner: tiago
--

ALTER TABLE ONLY scoremaster.card
    ADD CONSTRAINT fkrjuhhst8mclavtfueejmpr6br FOREIGN KEY (id_player) REFERENCES scoremaster.player(id);


--
-- PostgreSQL database dump complete
--

\unrestrict oBfVbCJTXPZXNTgFrJJaTHByDJQmeqnjLjNvQl9i2V2fswDRq1XGUrHbpyXLgsg

